Repository strongdm/accessbot, pull requests merged in 2021-09, with the labels that each got.

#113 Feat/fix grant exists
  e2e/test_accessbot_access.py
  e2e/test_accessbot_assign_role.py
  plugins/sdm/lib/approve_helper.py
  plugins/sdm/lib/resource_grant_helper.py
  plugins/sdm/lib/role_grant_helper.py
  plugins/sdm/lib/sdm_service.py
  plugins/sdm/lib/test_sdm_service.py
Labels: bug

#114 Feat/fix grant exists
  e2e/test_accessbot_access.py
  e2e/test_accessbot_assign_role.py
  plugins/sdm/lib/approve_helper.py
  plugins/sdm/lib/role_grant_helper.py
Labels: bug

#115 Feat/port issue 103
  e2e/test_accessbot_access.py
  e2e/test_accessbot_assign_role.py
  plugins/sdm/lib/approve_helper.py
  plugins/sdm/lib/resource_grant_helper.py
  plugins/sdm/lib/role_grant_helper.py
  plugins/sdm/lib/sdm_service.py
  plugins/sdm/lib/test_sdm_service.py
Labels: bug

#116 Feat/add toggle resources fuzzy match
  docs/CONFIGURE_ACCESSBOT.md
  e2e/test_accessbot_access.py
  e2e/test_common.py
  plugins/sdm/config_template.py
  plugins/sdm/lib/base_grant_helper.py
  plugins/sdm/lib/resource_grant_helper.py
  plugins/sdm/lib/role_grant_helper.py
Labels: enhancement

#118 Feat/add base show helper
  plugins/sdm/lib/base_show_helper.py
  plugins/sdm/lib/show_resources_helper.py
  plugins/sdm/lib/show_roles_helper.py
Labels: enhancement

#119 Feat/port issue 106
  e2e/test_accessbot_access.py
  e2e/test_accessbot_assign_role.py
  e2e/test_accessbot_show_roles.py
  plugins/sdm/lib/__init__.py
  plugins/sdm/lib/base_grant_helper.py
  plugins/sdm/lib/base_show_helper.py
  plugins/sdm/lib/resource_grant_helper.py
  plugins/sdm/lib/role_grant_helper.py
  plugins/sdm/lib/sdm_service.py
  plugins/sdm/lib/show_resources_helper.py
  plugins/sdm/lib/show_roles_helper.py
Labels: enhancement

#126 Add support to different timeouts per resource
  docs/CONFIGURE_ACCESSBOT.md
  e2e/test_accessbot_access.py
  e2e/test_common.py
  plugins/sdm/config_template.py
  plugins/sdm/lib/approve_helper.py
Labels: enhancement

#127 Add support to different timeouts per resource
  docs/CONFIGURE_ACCESSBOT.md
  e2e/test_accessbot_access.py
  e2e/test_common.py
  plugins/sdm/config_template.py
  plugins/sdm/lib/approve_helper.py
Labels: enhancement

#132 Feat/add alternative email support docs
  docs/CONFIGURE_ACCESSBOT.md
  docs/CONFIGURE_ALTERNATIVE_EMAILS.md
Labels: documentation
