Repository strongdm/accessbot, pull requests merged in 2022-10, with the labels that each got.

#279 Allow APPROVERS_CHANNEL_TAG on SDM Accounts
  docs/configure_accessbot/ACCESS_CONFIGURATION.md
  docs/configure_accessbot/CONFIGURE_ACCESSBOT.md
  e2e/slack/test_accessbot_slack_access.py
  e2e/slack/test_accessbot_slack_poller.py
  e2e/test_common.py
  plugins/sdm/lib/helper/base_evaluate_request_helper.py
  plugins/sdm/lib/helper/base_grant_helper.py
  plugins/sdm/lib/helper/poller_helper.py
  plugins/sdm/lib/test_util.py
Labels: enhancement

#307 Improve helmchart docs
  helm/README.md
Labels: documentation

#301 Add duration limit flag
  docs/configure_accessbot/CONFIGURE_ACCESSBOT.md
  e2e/slack/test_accessbot_slack_access.py
  e2e/test_common.py
  plugins/sdm/config_template.py
  plugins/sdm/lib/helper/resource_grant_helper.py
  requirements/common.txt
Labels: enhancement

#308 Add required reason template
  docs/configure_accessbot/CONFIGURE_ACCESSBOT.md
  e2e/slack/test_accessbot_slack_access.py
  plugins/sdm/lib/helper/resource_grant_helper.py
Labels: enhancement

#306 Health-check endpoint improvements
  Dockerfile
  config.py
  plugins/health-check/health_check.plug
  plugins/health-check/health_check.py
  plugins/health-check/health_check_helper.py
  plugins/sdm/accessbot.py
  plugins/sdm/lib/helper/__init__.py
  plugins/sdm/lib/helper/health_check_helper.py
Labels: enhancement

#309 Add deployment infrastructure docs
  README.md
  docs/deploy/INFRASTRUCTURES.md
Labels: enhancement

#315 Improve Workflow Builder Access Request Form docs and remove Accessform approach
  README.md
  docs/configure_accessbot/CONFIGURE_ACCESSBOT.md
  docs/deploy/FARGATE.md
  docs/ms-teams/CONFIGURE_MS_TEAMS.md
  docs/slack/CONFIGURE_ACCESSBOT_FORM.md
  docs/slack/CONFIGURE_ACCESSFORM.md
  docs/slack/CONFIGURE_WORKFLOW_BUILDER_ACCESSBOT_FORM.md
  tools/accessform/accessform-manifest.yaml
  tools/accessform/app.py
  tools/accessform/env-file.example
  tools/accessform/modal.py
  tools/accessform/requirements.txt
Labels: documentation, enhancement

#314 Fix wrong sender email when using ms teams alternative emails
  e2e/slack/test_accessbot_slack_access.py
  plugins/sdm/accessbot.py
  plugins/sdm/lib/helper/approve_helper.py
  plugins/sdm/lib/helper/base_evaluate_request_helper.py
  plugins/sdm/lib/helper/deny_helper.py
Labels: enhancement

#310 Add SDM account tags and Azure AD alternative emails in the whoami command
  e2e/ms-teams/test_accessbot_ms_teams_whoami.py
  e2e/slack/test_accessbot_slack_whoami.py
  e2e/test_common.py
  plugins/sdm/accessbot.py
  plugins/sdm/lib/helper/whoami_helper.py
  plugins/sdm/lib/platform/base_platform.py
  plugins/sdm/lib/platform/ms_teams_platform.py
  plugins/sdm/lib/platform/slack_platform.py
Labels: enhancement
