Repository strongdm/accessbot, pull requests merged in 2022-09, with the labels that each got.

#280 Add allow groups list for grant requests
  docs/configure_accessbot/CONFIGURE_ACCESSBOT.md
  e2e/slack/test_accessbot_slack_access.py
  e2e/slack/test_accessbot_slack_assign_role.py
  e2e/test_common.py
  plugins/sdm/config_template.py
  plugins/sdm/grant_request_type.py
  plugins/sdm/lib/helper/base_grant_helper.py
  plugins/sdm/lib/helper/base_show_helper.py
  plugins/sdm/lib/helper/resource_grant_helper.py
  plugins/sdm/lib/helper/role_grant_helper.py
  plugins/sdm/lib/helper/show_resources_helper.py
  plugins/sdm/lib/helper/show_roles_helper.py
  plugins/sdm/lib/test_util.py
  plugins/sdm/lib/util.py
Labels: enhancement

#292 Update ms teams docs and fix bot grant requests state handling
  README.md
  docs/CONFIGURE_LOCAL_ENV.md
  docs/ms-teams/CONFIGURE_MS_TEAMS.md
  docs/ms-teams/index.md
  docs/teams/CONFIGURE_MS_TEAMS.md
  e2e/slack/test_accessbot_slack_access.py
  plugins/sdm/accessbot.py
  plugins/sdm/lib/helper/approve_helper.py
  plugins/sdm/lib/helper/arguments_helper.py
  plugins/sdm/lib/helper/base_evaluate_request_helper.py
  plugins/sdm/lib/helper/base_grant_helper.py
  plugins/sdm/lib/helper/grant_request_helper.py
  plugins/sdm/lib/helper/resource_grant_helper.py
  plugins/sdm/lib/platform/base_platform.py
  plugins/sdm/lib/platform/ms_teams_platform.py
  plugins/sdm/lib/platform/slack_platform.py
Labels: documentation, enhancement

#296 Update Troubleshooting Docs w/ Error Message block
  docs/TROUBLESHOOTING.md
Labels: documentation
